### ISSUE TITLE
`object/is` returns true for functions

### ISSUE THREAD

**Issue by JRJurman** [medikoo/type#1]
Wasn't sure if this is intentional or not, but `object/is` returns true and `object/ensure` passes when you test a function.

![image](https://user-images.githubusercontent.com/326557/104109345-e546dd80-529a-11eb-8b99-bba8dbec30fe.png)

For my use case I actually need to verify that it is non-primitive, and not a function. In reality, I could understand functions being considered "non-primitive", but it looks like neither `primitive-object` or `object` cover my use case of only objects and arrays, unless I'm missing something...

**Comment by medikoo** [comment]
@JRJurman `object/is` simply confirms whether we deal with a value that's not a _primitive_.

If your use case is about confirming a JSON non-primitive value (so either plain object or array) it might be more accurate to  refer to `plain-object/is` and native `Array.isArray` (as `isPlainObject(value) || Array.isArray(value)`)

**Comment by JRJurman** [comment]
Makes sense. Thanks for the prompt answer (and the amazing library)!
